Navigation Component
acm-ucr/membership-portal pull request #40
Opened 2022-10-05 05:12 UTC by Arnav-Menon

first commit, pretty ugly ngl

2022-10-05 16:18 UTC, kninja99 commented on components/Navigation.jsx
> +      <h4 style={{float:"right", wordSpacing:"15px", paddingRight:"2%"}}>profile forms resources "general"</h4>
For styles we are using tailwind so try to avoid using inline css

2022-10-05 16:19 UTC, kninja99 commented on components/Navigation.jsx
> +      <img src={"../public/vercel.svg"} alt="acm@ucr" style={{float:"left"}}/>
Use the Image component from next.js

2022-10-05 16:21 UTC, kninja99 requested changes
Left comments in sections that need to be changed. Haven't loaded branch on my end to look but try to upload images so we can see how it looks.

##### Things to address

* for css styling use tailwind
*  change img element to be a Image component from next.js

2022-10-05 20:06 UTC, shahdivyank reviewed
Make sure to pass the CI checks as well: 

`npm run format` and `npm run eslint` will help you format the code and get you logs for the linting errors you have

2022-10-05 20:06 UTC, shahdivyank commented
Make sure to attach the issue to this pr as well

2022-10-06 19:59 UTC, Arnav-Menon commented
![Screenshot (4)](https://user-images.githubusercontent.com/70414572/194407028-34aaf8b5-09ad-4f7f-985a-a4a2d31b120c.png)

2022-10-06 20:01 UTC, Arnav-Menon commented
thanks for the comments guys. a couple of notes from me, I couldn't get the acm text to work for me, configuring the className with "text-acm-black" and without gives me the same results in the screenshot. Also I wasn't able to find the below image for the logo, which should go to the left of "member portal" 
![Screenshot_20221006_010043](https://user-images.githubusercontent.com/70414572/194407328-0af0d612-6e38-462f-a95f-65a59feaeede.png)

2022-10-08 18:39 UTC, shahdivyank approved these changes

2022-10-08 19:38 UTC, RayyanZaid approved these changes

2022-10-08 19:41 UTC, kninja99 approved these changes

2022-10-08 19:42 UTC, merged